canadata/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='blog'),
    # path('<int:inventory_id>/', views.item_detail, name='item_detail'),
    # ex: /polls/5/results/
    # path('<int:inventory_id>/results/', views.results, name='results'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
    # path('<int:question_id>/submit', views.get_data, name='get_data')
    ]

canadata/canadata/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

#urlpatterns = [
#    path('admin/', admin.site.urls),
#    path('inventory_explorer/', include('inventory_explorer.urls')),
#    ]

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('inventory_explorer/', include('inventory_explorer.urls')),
    path('visualizer/', include('visualizer.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

canadata/inventory_explorer/urls.py
from django.urls import path
from . import views

app_name = 'inventory_explorer'
urlpatterns = [
    path('', views.inventory_explorer, name='inventory_explorer'),
    path('<int:inventory_id>/', views.item_detail, name='item_detail'),
    # ex: /polls/5/results/
    path('<int:inventory_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/submit', views.get_data, name='get_data')
    ]

canadata/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

canadata/visualizer/urls.py
from django.urls import path
from . import views
app_name = 'visualizer'
urlpatterns = [
    path('', views.index, name='index'),
]

canadata/blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

canadata/inventory_explorer/models.py
from django.db import models
import datetime
from django.utils import timezone
from postgres_copy import CopyManager

class Inventory(models.Model):
    ref_number = models.CharField(max_length=25, blank=True, null=True)
    title_en = models.CharField(max_length=75, blank=True, null=True)
    description_en = models.CharField(max_length=1000, blank=True, null=True)
    publisher_en = models.CharField(max_length=200, blank=True, null=True)
    date_published = models.DateField(null=True, blank=True)
    language = models.CharField(max_length=20, blank=True, null=True)
    size = models.BigIntegerField(null=True, blank=True, default=0)
    eligible_for_release = models.CharField(max_length=5, blank=True, null=True)
    program_alignment_architecture_en = models.CharField(max_length=75, blank=True, null=True)
    portal_url_en = models.CharField(max_length=200, blank=False, default='NaN')
    user_votes = models.IntegerField(default=0)
    owner_org = models.CharField(max_length=75, blank=True, null=True)
    owner_org_title = models.CharField(max_length=75, blank=True, null=True)
    objects = CopyManager()

    def __str__(self):
        return self.title_en
#
# MyModel.objects.from_csv(
#     "./data.csv",  # The path to a source file (a Python file object is also acceptable)
#     dict(name='NAME', number='NUMBER')  # A crosswalk of model fields to CSV headers.
# )

canadata/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

canadata/visualizer/models.py
from django.db import models

canadata/blog/views.py
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from .models import Post

def post_list(request):
    post = Post.objects.order_by('-published_date')[:10]
    context = {'posts': post}
    return render(request, 'blog/blog.html', context)

canadata/inventory_explorer/views.py
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from .models import Inventory

from profile_data_script import profile

def inventory_explorer(request):
    titles = Inventory.objects.exclude(date_published__isnull=True).order_by('-date_published')[:1000]
    context = {'titles': titles}
    return render(request, 'inventory_explorer/inventory.html', context)

def item_detail(request, inventory_id):
    title = get_object_or_404(Inventory, pk=inventory_id)
    return render(request, 'inventory_explorer/item_detail.html', {'title': title})

def results(request, inventory_id):
    response = "You're looking at the results of poll %s."
    return HttpResponse(response % inventory_id)

def vote(request, inventory_id):
    return HttpResponse("You're voting on item %s." % inventory_id)

def get_data(request):
    response = HttpResponse(Inventory, content_type='text/plain')
    response_a = profile(response)
    return response_a

#name__contains='Smith'

canadata/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from .models import Question


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

canadata/visualizer/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return HttpResponse("Hello, world. You're at the visualizer index.")

canadata/blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Canadata Explorer</title>
        <link rel="stylesheet" href="{% static 'blog_style.css' %}">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="apple-touch-icon" sizes="180x180" href="/src/content/favicons/apple-touch-icon.png">
        <!-- <link rel="icon" type="image/png" sizes="32x32" href="/src/content/favicons/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/src/content/favicons/favicon-16x16.png">
        <link rel="manifest" href="/src/content/favicons/manifest.json"> -->
        <meta name="theme-color" content="#ffffff">
    </head>
      <ul id="stickymenu" class="solidblockmenu">
        <li><a href="/polls">Canadata</a></li>
        <li><a href="/inventory_explorer">Open Data Explorer</a></li>
        <li><a href="/visualizer">Visualizer</a></li>
        <li><a href="/blog">Canadata Blog</a></li>
        <li><a href="/about">About</a></li>
      </ul>
    <header>
      {% load static %}
      <img src="{% static 'blog/images/Flag_of_Canada.svg' %}" alt="My image"/>
      <h1>Open Canada Datasets</h1>
    </header>
    <body>
      {% block body %} {% endblock %}
    </body>
    <footer>

    </footer>
</html>

canadata/blog/templates/blog/blog.html
{% extends "blog/base.html" %}

{% block body %}
  {% if posts %}
    <ul class="container-items">
      {% for post in posts %}
        <h3>{{ post.title }}</h3>
        <div class="owner">{{ post.text }}</div>
        <div class="date">{{ post.published_date }}</div>

      {% endfor %}
    </ul>
  {% else %}
    <p>No posts are available.</p>
    {% endif %}
{% endblock %}
<!-- <a href="{% url 'inventory_explorer:item_detail' title.id %}" > </a> -->

canadata/blog/templates/blog/item_detail.html
{% load staticfiles %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="{% static 'style.css' %}">
<h1>{{ title }}</h1>
<p>{{ title.description_en }}</p>
<p><a href= "{{ title.portal_url_en }}" >Go to dataset portal.</a></p>

<form action="submit" method="post">
    {% csrf_token %}
    <!-- <input type="text" name="info"><br> -->
    <input type="submit" value="Get Data">
</form>

#page>div.logo+ul#navigation>li*5>a{Item $}

#page>(div.logo+ul#navigation>li)*5>a{Item $}

canadata/inventory_explorer/templates/inventory_explorer/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Canadata Explorer</title>
        <link rel="stylesheet" href="{% static 'inventory_explorer_style.css' %}">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="apple-touch-icon" sizes="180x180" href="/src/content/favicons/apple-touch-icon.png">
        <!-- <link rel="icon" type="image/png" sizes="32x32" href="/src/content/favicons/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/src/content/favicons/favicon-16x16.png">
        <link rel="manifest" href="/src/content/favicons/manifest.json"> -->
        <meta name="theme-color" content="#ffffff">
    </head>
      <ul id="stickymenu" class="solidblockmenu">
        <li><a href="/polls">Canadata</a></li>
        <li><a href="/inventory_explorer">Open Data Explorer</a></li>
        <li><a href="/visualizer">Visualizer</a></li>
        <li><a href="/blog">Canadata Blog</a></li>
        <li><a href="/about">About</a></li>
      </ul>
    <header>
      {% load static %}
      <img src="{% static 'inventory_explorer/images/Flag_of_Canada.svg' %}" alt="My image"/>
      <h1>Open Canada Datasets</h1>
    </header>
    <body>
      {% block body %} {% endblock %}
    </body>
    <footer>

    </footer>
</html>

canadata/inventory_explorer/templates/inventory_explorer/inventory.html
{% extends "inventory_explorer/base.html" %}

{% block body %}
  {% if titles %}
    <ul class="container-items">
      {% for title in titles %}
        <h3><a href={{ title.portal_url_en }}> {{ title.title_en }} </a></h3>
        <div class="owner">{{ title.owner_org_title }}</div>
        <div class="date">{{ title.date_published }}</div>

      {% endfor %}
    </ul>
  {% else %}
    <p>No datasets are available.</p>
    {% endif %}
{% endblock %}
<!-- <a href="{% url 'inventory_explorer:item_detail' title.id %}" > </a> -->

canadata/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

canadata/polls/templates/polls/index.html
{% load staticfiles %}
<html>
    <head>
        <title>Canadata Explorer</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

canadata/visualizer/templates/visualizer/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'survey:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

canadata/visualizer/templates/visualizer/index.html
<!doctype html>
<html>

  <head>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">

    <title>Spartan minimal UI kit</title>

    <link rel="stylesheet" href="//cdn.rawgit.com/mitjafelicijan/spartan/v1.7/dist/spartan.min.css">

    <script src="//cdn.rawgit.com/mitjafelicijan/spartan/v1.7/dist/spartan.min.js" defer></script>

  </head>

  <body>

    <section class="wrapper">
      <div class="row">
        <div class="col-12">
          <p>Content goes here ...</p>
        </div>
      </div>
    </section>

  </body>

</html>